### PR TITLE
Ar/edit docker file

### PR DESCRIPTION
**Pull request by zARODz11z**

### CODE REVIEW

**Comment by purple4reina** [comment]
I'm confused how these dockerfiles stopped working. Any idea why?

**Comment by zARODz11z** [comment]
@purple4reina I was getting  

=> ERROR [builder  8/11] ADD ./scripts/.src/datadog-agent.tgz /tmp/dd                                                       1.7s
------
 > [builder  8/11] ADD ./scripts/.src/datadog-agent.tgz /tmp/dd:
------
Dockerfile.build:27
--------------------
  25 |     
  26 |     # copy source files (/tgz gets unzip automatically by Docker)
  27 | >>> ADD ./scripts/.src/datadog-agent.tgz /tmp/dd
  28 |     
  29 |     # build the extension
--------------------
ERROR: failed to solve: lsetxattr /datadog-agent/releasenotes/notes/serverless-DD-SERVICE-MAPPING-594cc2cb7d090473.yaml: operation not supported

**Comment by zARODz11z** [comment]
there are other release notes with caps in it, idk why it was complaining about that one

**Comment by zARODz11z** [comment]
That release note is 3mo old and Dylan was able to release 2wks ago with no issue

**Pull request closed without merging**
